CREATE TABLE BusinessTutors (
	cf CHAR(16) NOT NULL PRIMARY KEY,
	business INTEGER NOT NULL,

	FOREIGN KEY (cf) REFERENCES Profiles(cf)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (business) REFERENCES Businesses(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE
);
