CREATE TABLE StudentClasses (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	level INTEGER NOT NULL,
	section VARCHAR(5) NOT NULL,
	year YEAR NOT NULL,

	handler CHAR(16),

	FOREIGN KEY (handler) REFERENCES Teachers(cf)
		ON UPDATE CASCADE
);
