CREATE TABLE StudentClasses (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	level INTEGER NOT NULL,
	section VARCHAR(5) NOT NULL,
	year YEAR NOT NULL,

	school INTEGER NOT NULL,
	course INTEGER NOT NULL,

	handler CHAR(16),

	FOREIGN KEY (school) REFERENCES Schools(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	FOREIGN KEY (course) REFERENCES Courses(id)
		ON UPDATE CASCADE
		ON DELETE CASCADE,

	FOREIGN KEY (handler) REFERENCES Teachers(cf)
		ON UPDATE CASCADE
);
